int imprimeDecre(int n);
int imprimePares(int n);
int imprimePrimos(int n);
int imprimeCresce(int n);
int elevar(int k, int n);
int mdc(int x, int y);
int mult(int n1, int n2);
int menorElemento(int *v, int n);
void inverteVetor(int *v, int n);
void imprimeVetor(int *v,int n);
int fatorial(int n);
void inverterString(char *v, int n);
int somarElementos(int *v, int n);
int palindroma(char *v, int n);
int contarCaractere(char *v, int n, char c);
int somatorio(int n);
float mediaVetor(int *v, int n);
int pertence(int *v, int n, int x);
int somaDigitos(int n);